In [1]:
import numpy as np

In [2]:
data1 = [1, 2, 3, 4, 5]
data1

[1, 2, 3, 4, 5]

In [3]:
data2 = [1, 2, 3, 3.5, 4]
data2

[1, 2, 3, 3.5, 4]

In [5]:
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [6]:
arr1.shape

(5,)

In [7]:
arr2 = np.array([1, 2, 3, 4, 5,])
arr2

array([1, 2, 3, 4, 5])

In [8]:
arr2.shape

(5,)

In [9]:
arr2.dtype

dtype('int32')

In [10]:
arr3 = np.array(data2)
arr3

array([1. , 2. , 3. , 3.5, 4. ])

In [11]:
arr3.shape

(5,)

In [12]:
arr3.dtype

dtype('float64')

In [13]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
print(arr4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
arr4.shape

(4, 3)

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.ones((2, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [26]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr1.shape

(2, 3)

In [28]:
arr2 = np.array([[10,11,12],[13,14,15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [29]:
arr2.shape

(2, 3)

In [30]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [31]:
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [32]:
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

In [33]:
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [34]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr1.shape

(2, 3)

In [36]:
arr3 = np.array([10 ,11, 12])
arr3

array([10, 11, 12])

In [37]:
arr3.shape

(3,)

In [38]:
arr1 + arr3

array([[11, 13, 15],
       [14, 16, 18]])

In [39]:
arr1 * arr3

array([[10, 22, 36],
       [40, 55, 72]])

In [40]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [41]:
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [46]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr1[0]

0

In [48]:
arr1[3]

3

In [49]:
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [50]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
arr2[0, 0]

1

In [53]:
arr2[2, :]

array([ 9, 10, 11, 12])

In [55]:
arr2[2, 3]

12

In [57]:
arr2[:,3]

array([ 4,  8, 12])

In [59]:
arr2 > 7  # 신기해! / 기존의 배열과 다르다.

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [60]:
arr2[arr2 > 7]

array([ 8,  9, 10, 11, 12])

In [58]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo','Park','Beomwoo'])
names

array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')